/*
# --- !Ups

create table "user" (
  "userID" VARCHAR NOT NULL PRIMARY KEY,
  "firstName" VARCHAR,
  "lastName" VARCHAR,
  "fullName" VARCHAR,
  "email" VARCHAR,
  "avatarURL" VARCHAR);
create table "logininfo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "providerID" VARCHAR NOT NULL,
  "providerKey" VARCHAR NOT NULL);
create table "userlogininfo" (
  "userID" VARCHAR NOT NULL,
  "loginInfoId" BIGINT NOT NULL);
create table "passwordinfo" (
  "hasher" VARCHAR NOT NULL,
  "password" VARCHAR NOT NULL,
  "salt" VARCHAR,
  "loginInfoId" BIGINT NOT NULL);
create table "oauth1info" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "token" VARCHAR NOT NULL,
  "secret" VARCHAR NOT NULL,
  "loginInfoId" BIGINT NOT NULL);
create table "oauth2info" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "accesstoken" VARCHAR NOT NULL,
  "tokentype" VARCHAR,
  "expiresin" INTEGER,
  "refreshtoken" VARCHAR,
  "logininfoid" BIGINT NOT NULL);
create table "openidinfo" (
  "id" VARCHAR NOT NULL PRIMARY KEY,
  "logininfoid" BIGINT NOT NULL);
create table "openidattributes" (
  "id" VARCHAR NOT NULL,
  "key" VARCHAR NOT NULL,
  "value" VARCHAR NOT NULL);


# --- !Downs

drop table "openidattributes";
drop table "openidinfo";
drop table "oauth2info";
drop table "oauth1info";
drop table "passwordinfo";
drop table "userlogininfo";
drop table "logininfo";
drop table "user";
*/
#`play_slick_silhouette_db`.

# --- !Ups

create table `play_slick_silhouette_db`.`user` (
  `userID` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45),
  `lastName` VARCHAR(45),
  `fullName` VARCHAR(45),
  `email` VARCHAR(45),
  `avatarURL` VARCHAR(45),
  PRIMARY KEY (`userID`));
create table `play_slick_silhouette_db`.`logininfo` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `providerID` VARCHAR(45) NOT NULL,
  `providerKey` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));
create table `play_slick_silhouette_db`.`userlogininfo` (
  `userID` VARCHAR(45) NOT NULL,
  `loginInfoId` BIGINT NOT NULL);
create table `play_slick_silhouette_db`.`passwordinfo` (
  `hasher` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45),
  `loginInfoId` BIGINT NOT NULL);
create table `play_slick_silhouette_db`.`oauth1info` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `secret` VARCHAR(45) NOT NULL,
  `loginInfoId` BIGINT NOT NULL,
  PRIMARY KEY (`id`));
create table `play_slick_silhouette_db`.`oauth2info` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `accesstoken` VARCHAR(45) NOT NULL,
  `tokentype` VARCHAR(45),
  `expiresin` INTEGER,
  `refreshtoken` VARCHAR(45),
  `logininfoid` BIGINT NOT NULL,
  PRIMARY KEY (`id`));
create table `play_slick_silhouette_db`.`openidinfo` (
  `id` VARCHAR(45) NOT NULL,
  `logininfoid` BIGINT NOT NULL,
  PRIMARY KEY (`id`));
create table `play_slick_silhouette_db`.`openidattributes` (
  `id` VARCHAR(45) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL);


# # --- !Downs
#
# drop table `openidattributes`;
# drop table `openidinfo`;
# drop table `oauth2info`;
# drop table `oauth1info`;
# drop table `passwordinfo`;
# drop table `userlogininfo`;
# drop table `logininfo`;
# drop table `user`;
